config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.views import defaults as default_views
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import TemplateView
from allauth.account.views import ConfirmEmailView
from rest_framework_jwt.views import obtain_jwt_token, refresh_jwt_token

from masteraula.users.views import null_view


urlpatterns = [
    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),

    # Your stuff: custom urls includes go here
    url(r'', include('masteraula.questions.urls', namespace='masteraula.questions')),
    url(r'', include('masteraula.users.urls', namespace='masteraula.users')),
    url(r'^reports/', include('masteraula.reports.urls', namespace='reports')),
    url(r'^pages/', include('masteraula.pages.urls', namespace='pages')),

    # Workaround to deal with some urls https://github.com/Tivix/django-rest-auth/issues/292
    url(r'^auth/registration/account-email-verification-sent/', null_view, name='account_email_verification_sent'),
    url(r'^auth/registration/account-confirm-email/', null_view, name='account_confirm_email'),
    url(r'^auth/registration/password-reset/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', null_view, name='password_reset_confirm'),
    
    url(r'^auth/', include('rest_auth.urls')),
    url(r'^auth/refresh-login', refresh_jwt_token),
    url(r'^auth/registration/', include('rest_auth.registration.urls')),

    url(r'^accounts/', include('allauth.urls'), name='socialaccount_signup'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
        url(r'^search/', include('haystack.urls')),
    ]
    if  'silk' in settings.INSTALLED_APPS:
        urlpatterns += [url(r'^silk/', include('silk.urls', namespace='silk'))]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns += [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ]

masteraula/pages/urls.py
from django.conf import settings
from django.conf.urls import url, include
from rest_framework.routers import DefaultRouter, SimpleRouter

from rest_framework_jwt.views import obtain_jwt_token, verify_jwt_token
from rest_framework_swagger.views import get_swagger_view

from . import views

# Create a router and register our viewsets with it.
router = SimpleRouter()
if settings.DEBUG: 
    router = DefaultRouter()

router.register(r'terms_use', views.TermsUseViewSet, base_name='terms_use')

urlpatterns = [
    url(r'^', include(router.urls)),
]

masteraula/reports/urls.py
from django.conf import settings
from django.conf.urls import url, include

from . import views
from . import statements_views
from . import alternatives_views
from . import objects_views

urlpatterns = [
    url(r'^$', views.ReportsView.as_view(), name='reports_home'),
    url(r'^uncategorized_questions/$', views.UncategorizedTagsView.as_view(), name='uncategorized_questions'),
    url(r'^number_documents/$', views.NumberDocumentsView.as_view(), name='number_documents'),
    url(r'^data_users_school/$', views.DataSchoolView.as_view(), name='data_users_school'),
    url(r'^data_users/$', views.DataUsersView.as_view(), name='data_users'),
    url(r'^questions_per_topic/$', views.QuestionPerTopicView.as_view(), name='questions_per_topic'),

    url(r'^statements_with_div/$', statements_views.StatementsWithDivView.as_view(), name='statements_with_div'),
    url(r'^statements_with_texto_associado/$', statements_views.StatementsWithTextoAssociado.as_view(), name='statements_with_texto_associado'),
    url(r'^statements_with_br/$', statements_views.StatementsWithBrInsideP.as_view(), name='statements_with_br'),
    url(r'^statements_with_p_inside_p/$', statements_views.StatementsWithPInsideP.as_view(), name='statements_with_p_inside_p'),
    url(r'^statements_with_empty_p/$', statements_views.StatementsWithEmptyP.as_view(), name='statements_with_empty_p'),
    url(r'^statements_with_strong_em/$', statements_views.StatementsWithBoldItalic.as_view(), name='statements_with_strong_em'),
    url(r'^statements_with_sup_sub/$', statements_views.StatementsWithSupSub.as_view(), name='statements_with_sup_sub'),
    url(r'^statements_with_line_height/$', statements_views.StatementsWithLineHeight.as_view(), name='statements_with_line_height'),
    url(r'^statements_tags_p_space/$', statements_views.StatementsTagsPSpace.as_view(), name='statements_tags_p_space'),
    url(r'^statements_all/$', statements_views.StatementsAllFilter.as_view(), name='statements_all'),
   
    url(r'^has_learning_object/$', views.StatementLearningObject.as_view(), name='has_learning_object'),
    url(r'^objects_without_source/$', views.ObjectsWithoutSource.as_view(), name='objects_without_source'),

    url(r'^objects_with_div/$', objects_views.ObjectsWithDivView.as_view(), name='objects_with_div'),
    url(r'^objects_with_texto_associado/$', objects_views.ObjectsWithTextoAssociado.as_view(), name='objects_with_texto_associado'),
    url(r'^objects_with_br/$', objects_views.ObjectsWithBrInsideP.as_view(), name='objects_with_br'),
    url(r'^objects_with_p_inside_p/$', objects_views.ObjectsWithPInsideP.as_view(), name='objects_with_p_inside_p'),
    url(r'^objects_with_empty_p/$', objects_views.ObjectsWithEmptyP.as_view(), name='objects_with_empty_p'),
    url(r'^objects_with_strong_em/$', objects_views.ObjectsWithBoldItalic.as_view(), name='objects_with_strong_em'),
    url(r'^objects_with_sup_sub/$', objects_views.ObjectsWithSupSub.as_view(), name='objects_with_sup_sub'),
    url(r'^objects_with_line_height/$', objects_views.ObjectsWithLineHeight.as_view(), name='objects_with_line_height'),
    url(r'^objects_tags_p_space/$', objects_views.ObjectsTagsPSpace.as_view(), name='objects_tags_p_space'),
    url(r'^objects_all/$', objects_views.ObjectsAllFilter.as_view(), name='objects_all'),

    # url(r'^objects_with_div/$', objects_views.ObjectsWithDivView.as_view(), name='objects_with_div'),
    # url(r'^objects_with_texto_associado/$', objects_views.ObjectsWithTextoAssociado.as_view(), name='objects_with_texto_associado'),
    # url(r'^objects_with_br/$', objects_views.ObjectsWithBrInsideP.as_view(), name='objects_with_br'),
    # url(r'^objects_with_p_inside_p/$', objects_views.ObjectsWithPInsideP.as_view(), name='objects_with_p_inside_p'),
    # url(r'^objects_with_empty_p/$', objects_views.ObjectsWithEmptyP.as_view(), name='objects_with_empty_p'),
    # url(r'^objects_with_strong_em/$', objects_views.ObjectsWithBoldItalic.as_view(), name='objects_with_strong_em'),
    # url(r'^objects_with_sup_sub/$', objects_views.ObjectsWithSupSub.as_view(), name='objects_with_sup_sub'),
    # url(r'^objects_with_line_height/$', objects_views.ObjectsWithLineHeight.as_view(), name='objects_with_line_height'),
    url(r'^alternatives_all/$', alternatives_views.AlternativesAllFilter.as_view(), name='alternatives_all'),

    url(r'^statement_update/$', views.StatemensUpdateView.as_view(), name='update_with_div'),
    url(r'^learning_object_update/$', views.LearningObjectUpdateView.as_view(), name='update_learning_object'),
    url(r'^alternative_update/$', views.AlternativeUpdateView.as_view(), name='alternative_update'),
]

masteraula/users/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf import settings
from django.conf.urls import url, include
from rest_framework.routers import DefaultRouter, SimpleRouter
from rest_auth.registration.views import (
    SocialAccountListView, SocialAccountDisconnectView
)

from . import views

router = SimpleRouter()
if settings.DEBUG: 
    router = DefaultRouter()

router.register(r'cities', views.CityViewSet, base_name='cities-list')
router.register(r'states', views.StateViewSet, base_name='states-list')
router.register(r'school', views.SchoolViewSet, base_name='school')
router.register(r'dashboard', views.DashboardViewSet, base_name='dashboard')
router.register(r'contact', views.ContactViewSet, base_name='contact')


urlpatterns = [
    url(r'^', include(router.urls)),
    url(
        regex=r'^resend_confirmation_email$',
        view=views.UserConfirmationEmailView.as_view(),
        name='list'
    ),
    url(r'^rest-auth/sign-in/facebook/$', views.FacebookLogin.as_view(), name='fb_login'),
    url(r'^rest-auth/sign-in/google/$', views.GoogleLogin.as_view(), name='google_login'),
    url(r'^rest-auth/sign-up/facebook/$', views.FacebookSignup.as_view(), name='fb_signup'),
    url(r'^rest-auth/sign-up/google/$', views.GoogleSignup.as_view(), name='google_signup'),
    url(r'^rest-auth/connect/facebook/$', views.FacebookConnect.as_view(), name='fb_connect'),
    url(r'^rest-auth/connect/google/$', views.GoogleConnect.as_view(), name='google_connect'),
    url(
        r'^socialaccounts/$',
        SocialAccountListView.as_view(),
        name='social_account_list'
    ),
    url(
        r'^socialaccounts/(?P<pk>\d+)/disconnect/$',
        SocialAccountDisconnectView.as_view(),
        name='social_account_disconnect'
    )
]

masteraula/pages/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

import datetime
from dateutil import relativedelta

#populated by fixture
class TermsUse (models.Model):
    content = models.TextField()
    last_update = models.DateTimeField(auto_now=True)

masteraula/reports/models.py
from django.db import models

# Create your models here.

masteraula/users/forms.py
from django import forms

class SignupForm(forms.Form):

    def signup(self, request, user):
        pass

masteraula/pages/views.py
# -*- coding: utf-8 -*-
import os
import time
import datetime
import operator

from functools import reduce

from rest_framework import (generics, response, viewsets, status, mixins, exceptions, pagination, permissions)
from rest_framework.decorators import detail_route, list_route, permission_classes
from rest_framework.response import Response

from django.http import HttpResponse, FileResponse, HttpResponseBadRequest
from django.shortcuts import get_object_or_404
from django.template.response import TemplateResponse

from .models import (TermsUse,)

from . import serializers as serializers

class TermsUseViewSet(viewsets.ReadOnlyModelViewSet):
    queryset = TermsUse.objects.all().order_by('id')
    serializer_class = serializers.TermsUseSerializer
    pagination_class = None

masteraula/users/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.core.urlresolvers import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

from allauth.socialaccount.providers.facebook.views import FacebookOAuth2Adapter
from allauth.socialaccount.providers.google.views import GoogleOAuth2Adapter
from allauth.socialaccount.providers.oauth2.client import OAuth2Client
from rest_auth.registration.views import SocialLoginView, SocialConnectView

from rest_framework import status
from rest_framework import viewsets
from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework.generics import GenericAPIView
from rest_framework.permissions import AllowAny, IsAuthenticated

from django.contrib.auth.mixins import LoginRequiredMixin

from .models import User, City, State, School, Subscription, Contact
from .serializers import CitySerializer, StateSerializer, SchoolSerializer,ResendConfirmationEmailSerializer, SocialOnlyLoginSerializer, SubscriptionSerializer, DashboardSerializer, ContactSerializer


class CityViewSet(viewsets.ReadOnlyModelViewSet):
    pagination_class = None
    serializer_class = CitySerializer
    queryset = City.objects.all()

    def get_queryset(self):
        queryset = City.objects.all()
        if 'uf' not in self.request.query_params:
            return None
        uf = self.request.query_params['uf']
        queryset = queryset.filter(uf=uf)
        return queryset

class StateViewSet(viewsets.ReadOnlyModelViewSet):
    pagination_class = None
    serializer_class = StateSerializer
    queryset = State.objects.all()
    
class SchoolViewSet(viewsets.ModelViewSet):
    pagination_class = None
    serializer_class = SchoolSerializer
    queryset = School.objects.all()

class SubscriptionViewSet(viewsets.ModelViewSet):
    pagination_class = None
    serializer_class = SubscriptionSerializer
    queryset = Subscription.objects.all()

class UserConfirmationEmailView(GenericAPIView):
    permission_classes = (AllowAny,)
    serializer_class = ResendConfirmationEmailSerializer

    def post(self, request, *args, **kwargs):
        self.serializer = self.get_serializer(data=request.data,
                                                context={'request': request})
        self.serializer.is_valid(raise_exception=True)            
        return Response({"status": "Confirmation e-mail was sent with success"}, status=status.HTTP_200_OK)

class FacebookSignup(SocialLoginView):
    adapter_class = FacebookOAuth2Adapter

class GoogleSignup(SocialLoginView):
    adapter_class = GoogleOAuth2Adapter
    client_class = OAuth2Client

class FacebookLogin(SocialLoginView):
    adapter_class = FacebookOAuth2Adapter

    serializer_class = SocialOnlyLoginSerializer

class GoogleLogin(SocialLoginView):
    adapter_class = GoogleOAuth2Adapter
    client_class = OAuth2Client

    serializer_class = SocialOnlyLoginSerializer

class FacebookConnect(SocialConnectView):
    adapter_class = FacebookOAuth2Adapter

class GoogleConnect(SocialConnectView):
    adapter_class = GoogleOAuth2Adapter
    client_class = OAuth2Client

class DashboardViewSet(viewsets.ReadOnlyModelViewSet):
    serializer_class = DashboardSerializer
    permission_classes = (IsAuthenticated, )

    def get_queryset(self):
        queryset = User.objects.filter(id=self.request.user.id).order_by('-id')
        return queryset

class ContactViewSet(viewsets.ModelViewSet):
    queryset = Contact.objects.all()
    pagination_class = None
    serializer_class = ContactSerializer

    def create(self, request, *args, **kwargs):             
        serializer = self.get_serializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        self.perform_create(serializer)
        headers = self.get_success_headers(serializer.data)
        return Response({"Success": "Message sent."}, status=status.HTTP_201_CREATED, headers=headers)

@api_view()
def null_view(request):
    return Response(status=status.HTTP_400_BAD_REQUEST)

masteraula/templates/reports/base.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<h2>Relatórios Administrativos</h2>
<br>
<a href="{% url 'reports:number_documents' %}">Quantidade de provas do usuário</a>
<br>
<a href="{% url 'reports:data_users_school' %}">Informações dos usuários por escola</a>
<br>
<a href="{% url 'reports:data_users' %}">Informações gerais dos usuários</a>
<br>
<a href="{% url 'reports:questions_per_topic' %}">Questões por tópico</a>
<br>
<br>
<h2>Correções de conteúdo</h2>
<br>
<h5>Questões</h5>
<a href="{% url 'reports:uncategorized_questions' %}">Questões não categorizadas</a>
<br>
<a href="{% url 'reports:statements_with_div' %}">Questões com tag div</a>
<br>
<a href="{% url 'reports:statements_with_texto_associado' %}">Questões com texto associado</a>
<br>
<a href="{% url 'reports:statements_with_br' %}">Questões com tag br</a>
<br>
<a href="{% url 'reports:statements_with_p_inside_p' %}">Questões com tag p dentro de p</a>
<br>
<a href="{% url 'reports:statements_with_empty_p' %}">Questões com tags p vazias</a>
<br>
<a href="{% url 'reports:statements_with_strong_em' %}">Questões com tag strong ou em</a>
<br>
<a href="{% url 'reports:statements_with_sup_sub' %}">Questões com tag sup ou sub</a>
<br>
<a href="{% url 'reports:statements_with_line_height' %}">Questões com line height</a>
<br>
<a href="{% url 'reports:statements_tags_p_space' %}">Questões com tags p sem espaço</a>
<br>
<a href="{% url 'reports:statements_all' %}">Questões com todos os filtros</a>
<br>
<h5>Objetos de aprendizagem</h5>
<a href="{% url 'reports:objects_with_div' %}">Objetos de aprendizagem  com tag div</a>
<br>
<a href="{% url 'reports:objects_with_texto_associado' %}">Objetos de aprendizagem com texto associado</a>
<br>
<a href="{% url 'reports:objects_with_br' %}">Objetos de aprendizagem com tag br</a>
<br>
<a href="{% url 'reports:objects_with_p_inside_p' %}">Objetos de aprendizagem com tag p dentro de p</a>
<br>
<a href="{% url 'reports:objects_with_empty_p' %}">Objetos de aprendizagem com tags p vazias</a>
<br>
<a href="{% url 'reports:objects_with_strong_em' %}">Objetos de aprendizagem com tag strong ou em</a>
<br>
<a href="{% url 'reports:objects_with_sup_sub' %}">Objetos de aprendizagem com tag sup ou sub</a>
<br>
<a href="{% url 'reports:objects_with_line_height' %}">Objetos de aprendizagem com line height</a>
<br>
<a href="{% url 'reports:objects_tags_p_space' %}">Objetos de aprendizagem com tags p sem espaço</a>
<br>
<a href="{% url 'reports:objects_all' %}">Objetos de aprendizagem com todos os filtros</a>
<br>
<a href="{% url 'reports:objects_without_source' %}">Objetos sem fonte</a>
<br>
<a href="{% url 'reports:has_learning_object' %}">Possiveis objetos</a>
<br>
<br>
<h5>Alternativas</h5>
<a href="{% url 'reports:alternatives_all' %}">Alternativas com todos os filtros</a>
<br>



{% endblock %}

masteraula/templates/reports/data_users.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<h1>Informações dos usuários</h1>
<br>

<form method="POST">
    {% csrf_token %}
    <br>               
    <strong> Por favor, insira os dados para exportar as informações dos usuários </strong><br>
    <br>
    <br>  
    Data: 
    <input type="month" name="date" min="2018-01"> 
    
    <br> 
    <br>
    <strong> Insira os IDs para exportar os dados de usuários específicos ou deixe em branco para exportar todos</strong><br>
    
    <br>  
    Usuário: <input id="user" type="text" name="id_users"> 
    <h6>*Separados por vírgulas e sem espaço</h6>
  
    <br> 
    {% if not_found %}
    <br>
        <div class="alert alert-danger">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            Usuário inexistente {{users}}            

        </div>
        
    {% endif %}
    {% if not_found_date %}
    <br>
        <div class="alert alert-danger">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            Ano: A partir de 2018            

        </div>
        
    {% endif %}
    
    <br>
    <br>    
    <input type="submit" value="Enviar">
</form>

{% endblock %}

masteraula/templates/reports/data_users_school.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<h1>Informações dos usuários por escola</h1>
<br>

<form method="POST">
    {% csrf_token %}
    <br>               
    <strong> Selecione a escola para exportar as informações dos usuários </strong><br>
    <br> 
    <label for="user"> Escola: </label>
   
    <select name="id_school">
        <option selected="selected" disabled>Selecione</option>
        {% for school in data %}
            <option value="{{school.id}}">{{school.name}}</option>
        {% endfor %} 
      </select>
    <br>
    <br>  
    Data: 
    <input type="month" name="date"> 
    
    <br> 
    <br>
    <strong> Insira os IDs para exportar os dados de usuários específicos ou deixe em branco para exportar todos</strong><br>
    
    <br>  
    Usuário: <input id="user" type="text" name="id_users"> 
    <h6>*Separados por vírgulas e sem espaço</h6>
  
    <br> 
    {% if not_found %}
    <br>
        <div class="alert alert-danger">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            Usuário inexistente {{users}}            

        </div>
        
    {% endif %}
    <br>
    <br>    
    <input type="submit" value="Enviar">
</form>

{% endblock %}

masteraula/templates/reports/edit_alternative_text.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<h1>{{header}}</h1>


<form method="POST">
    {% csrf_token %}
    {% for discipline in disciplines %}
        <input type="checkbox" name="disciplines" value="{{discipline.id}}">
            {{discipline.name}}
        </input><br>
    {% endfor %}
    <input type="submit" value="Enviar">
</form>
{% for results in data %}
    <div id="questao{{results.0}}">
    <hr>
    <h1>Alternativa {{ results.0 }}</h1>
    {{results.3}}
    <table style='width: 100%' border="">
        <tr>
            <td style='width: 50%'>
                <textarea id='txtstmt{{results.0}}' onchange="replacestmt({{results.0}})" style='width: 100%; height: 300px'>{{ results.1 }}</textarea>
            </td>
            <td style='width: 50%'>
                <textarea id='txtclean{{results.0}}' onchange="replaceclean({{results.0}})" style='width: 100%; height: 300px'>{{ results.2 }}</textarea>
            </td>
        </tr>
        <tr>
            <td id='stmt{{results.0}}'>
                {{ results.1 |safe}}
            </td>
            <td id='clean{{results.0}}'>
                {{ results.2 |safe}}
            </td>
        </tr>
    </table>
    <button onclick="update({{results.0}})">Modificar</button>
    <span id="status{{results.0}}"></span>
    </div>
{% endfor %}

<script>
function replacestmt(id) {
    const stmt = document.getElementById("txtstmt" + id).value;
    document.getElementById("stmt"+id).innerHTML = stmt;
}

function replaceclean(id) {
    const clean = document.getElementById("txtclean" + id).value;
    document.getElementById("clean"+id).innerHTML = clean;
}

function update(id) {
    const  token = "{{ csrf_token }}";

    const data = {
        id, 
        text: document.getElementById("txtclean" + id).value
    }

    $.ajax({
        type: "POST",
        url: "/reports/alternative_update/",
        dataType: 'json',
        contentType: 'application/json',
        data: JSON.stringify(data),
        headers: { "X-CSRFToken": token },
    }).done(function() {
        document.getElementById('status' + id).innerHTML = "Modificado"
    })
    .fail(function() {
        alert( "error" );
    });
}
</script>

{% endblock %}

masteraula/templates/reports/edit_object_text.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<h1>{{header}}</h1>



<form method="POST">
    {% csrf_token %}
    {% for discipline in disciplines %}
        <input type="checkbox" name="disciplines" value="{{discipline.id}}">
            {{discipline.name}}
        </input><br>
    {% endfor %}
    <input type="submit" value="Enviar">
</form>
{% for results in data %}
    <div id="lo{{results.0}}">
    <hr>
    <h1>Objeto {{ results.0 }}</h1>
    {{results.3}}
    <table style='width: 100%' border="">
        <tr>
            <td style='width: 50%'>
                <textarea id='txtstmt{{results.0}}' onchange="replacestmt({{results.0}})" style='width: 100%; height: 300px'>{{ results.1 }}</textarea>
            </td>
            <td style='width: 50%'>
                <textarea id='txtclean{{results.0}}' onchange="replaceclean({{results.0}})" style='width: 100%; height: 300px'>{{ results.2 }}</textarea>
            </td>
        </tr>
        <tr>
            <td id='stmt{{results.0}}'>
                {{ results.1 |safe}}
            </td>
            <td id='clean{{results.0}}'>
                {{ results.2 |safe}}
            </td>
        </tr>
    </table>
    <button onclick="update({{results.0}})">Modificar</button>
    <span id="status{{results.0}}"></span>
    </div>
{% endfor %}

<script>
function replacestmt(id) {
    const stmt = document.getElementById("txtstmt" + id).value;
    document.getElementById("stmt"+id).innerHTML = stmt;
}

function replaceclean(id) {
    const clean = document.getElementById("txtclean" + id).value;
    document.getElementById("clean"+id).innerHTML = clean;
}

function update(id) {
    const  token = "{{ csrf_token }}";
    const new_text = document.getElementById("txtclean" + id)

    const data = { 
        id,
        text: new_text ? new_text.value : null,
        source: null
    }

    $.ajax({
        type: "POST",
        url: "/reports/learning_object_update/",
        dataType: 'json',
        contentType: 'application/json',
        data: JSON.stringify(data),
        headers: { "X-CSRFToken": token },
    }).done(function() {
        document.getElementById('status' + id).innerHTML = "Modificado"
    })
    .fail(function() {
        alert( "error" );
    });
}
</script>

{% endblock %}

masteraula/templates/reports/edit_question_statement.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<h1>{{header}}</h1>


<form method="POST">
    {% csrf_token %}
    {% for discipline in disciplines %}
        <input type="checkbox" name="disciplines" value="{{discipline.id}}">
            {{discipline.name}}
        </input><br>
    {% endfor %}
    <input type="submit" value="Enviar">
</form>
{% for results in data %}
    <div id="questao{{results.0}}">
    <hr>
    <h1>Questao {{ results.0 }}</h1>
    {{results.3}}
    <table style='width: 100%' border="">
        <tr>
            <td style='width: 50%'>
                <textarea id='txtstmt{{results.0}}' onchange="replacestmt({{results.0}})" style='width: 100%; height: 300px'>{{ results.1 }}</textarea>
            </td>
            <td style='width: 50%'>
                <textarea id='txtclean{{results.0}}' onchange="replaceclean({{results.0}})" style='width: 100%; height: 300px'>{{ results.2 }}</textarea>
            </td>
        </tr>
        <tr>
            <td id='stmt{{results.0}}'>
                {{ results.1 |safe}}
            </td>
            <td id='clean{{results.0}}'>
                {{ results.2 |safe}}
            </td>
        </tr>
    </table>
    <button onclick="update({{results.0}})">Modificar</button>
    <span id="status{{results.0}}"></span>
    </div>
{% endfor %}

<script>
function replacestmt(id) {
    const stmt = document.getElementById("txtstmt" + id).value;
    document.getElementById("stmt"+id).innerHTML = stmt;
}

function replaceclean(id) {
    const clean = document.getElementById("txtclean" + id).value;
    document.getElementById("clean"+id).innerHTML = clean;
}

function update(id) {
    const  token = "{{ csrf_token }}";

    const data = {
        id, 
        statement: document.getElementById("txtclean" + id).value
    }

    $.ajax({
        type: "POST",
        url: "/reports/statement_update/",
        dataType: 'json',
        contentType: 'application/json',
        data: JSON.stringify(data),
        headers: { "X-CSRFToken": token },
    }).done(function() {
        document.getElementById('status' + id).innerHTML = "Modificado"
    })
    .fail(function() {
        alert( "error" );
    });
}
</script>

{% endblock %}